using CoralLedger.Blue.Domain.Common;
using CoralLedger.Blue.Domain.Enums;

namespace CoralLedger.Blue.Domain.Entities;

/// <summary>
/// Configurable alert rule for monitoring marine conditions
/// </summary>
public class AlertRule : BaseEntity
{
    public required string Name { get; set; }
    public string? Description { get; set; }

    /// <summary>
    /// Type of alert (Bleaching, Fishing, VesselInMPA, etc.)
    /// </summary>
    public required AlertType Type { get; set; }

    /// <summary>
    /// Severity level of alerts generated by this rule
    /// </summary>
    public AlertSeverity Severity { get; set; } = AlertSeverity.Medium;

    /// <summary>
    /// Whether this rule is currently active
    /// </summary>
    public bool IsActive { get; private set; } = true;

    /// <summary>
    /// JSON-serialized conditions for the rule
    /// </summary>
    public required string Conditions { get; set; }

    /// <summary>
    /// Optional: specific MPA to monitor (null = all MPAs)
    /// </summary>
    public Guid? MarineProtectedAreaId { get; set; }
    public MarineProtectedArea? MarineProtectedArea { get; set; }

    /// <summary>
    /// Notification channels (Email, Push, Dashboard)
    /// </summary>
    public NotificationChannel NotificationChannels { get; private set; } = NotificationChannel.Dashboard;

    /// <summary>
    /// Email addresses for notifications (comma-separated)
    /// </summary>
    public string? NotificationEmails { get; private set; }

    /// <summary>
    /// Cooldown period between alerts (prevents spam)
    /// </summary>
    public TimeSpan CooldownPeriod { get; private set; } = TimeSpan.FromHours(1);

    /// <summary>
    /// Last time this rule triggered an alert
    /// </summary>
    public DateTime? LastTriggeredAt { get; private set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; private set; }

    /// <summary>
    /// Alerts generated by this rule
    /// </summary>
    public ICollection<Alert> Alerts { get; set; } = new List<Alert>();

    /// <summary>
    /// Creates a new alert rule
    /// </summary>
    public static AlertRule Create(
        string name,
        AlertType type,
        string conditions,
        string? description = null,
        AlertSeverity severity = AlertSeverity.Medium,
        Guid? marineProtectedAreaId = null,
        NotificationChannel notificationChannels = NotificationChannel.Dashboard,
        string? notificationEmails = null,
        TimeSpan? cooldownPeriod = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentException.ThrowIfNullOrWhiteSpace(conditions);

        return new AlertRule
        {
            Name = name,
            Type = type,
            Conditions = conditions,
            Description = description,
            Severity = severity,
            MarineProtectedAreaId = marineProtectedAreaId,
            NotificationChannels = notificationChannels,
            NotificationEmails = notificationEmails,
            CooldownPeriod = cooldownPeriod ?? TimeSpan.FromHours(1),
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Activates the rule
    /// </summary>
    public void Activate()
    {
        if (IsActive)
        {
            return; // Already active, no-op
        }

        IsActive = true;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Deactivates the rule
    /// </summary>
    public void Deactivate()
    {
        if (!IsActive)
        {
            return; // Already inactive, no-op
        }

        IsActive = false;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Updates the rule conditions
    /// </summary>
    public void UpdateConditions(string conditions)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(conditions);

        Conditions = conditions;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Records that this rule triggered an alert
    /// </summary>
    public void RecordTrigger()
    {
        LastTriggeredAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Checks if the rule can trigger (cooldown period has elapsed)
    /// </summary>
    public bool CanTrigger()
    {
        if (!IsActive)
        {
            return false;
        }

        if (!LastTriggeredAt.HasValue)
        {
            return true;
        }

        return DateTime.UtcNow - LastTriggeredAt.Value >= CooldownPeriod;
    }

    /// <summary>
    /// Updates notification settings
    /// </summary>
    public void UpdateNotificationSettings(
        NotificationChannel channels,
        string? emails = null,
        TimeSpan? cooldownPeriod = null)
    {
        if (channels.HasFlag(NotificationChannel.Email) && string.IsNullOrWhiteSpace(emails))
        {
            throw new ArgumentException("Email addresses required when Email channel is enabled.", nameof(emails));
        }

        if (cooldownPeriod.HasValue && cooldownPeriod.Value < TimeSpan.Zero)
        {
            throw new ArgumentException("Cooldown period cannot be negative.", nameof(cooldownPeriod));
        }

        NotificationChannels = channels;
        NotificationEmails = emails;

        if (cooldownPeriod.HasValue)
        {
            CooldownPeriod = cooldownPeriod.Value;
        }

        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Updates the rule severity
    /// </summary>
    public void UpdateSeverity(AlertSeverity severity)
    {
        Severity = severity;
        UpdatedAt = DateTime.UtcNow;
    }
}
