using CoralLedger.Domain.Common;
using CoralLedger.Domain.Enums;

namespace CoralLedger.Domain.Entities;

/// <summary>
/// Configurable alert rule for monitoring marine conditions
/// </summary>
public class AlertRule : BaseEntity
{
    public required string Name { get; set; }
    public string? Description { get; set; }

    /// <summary>
    /// Type of alert (Bleaching, Fishing, VesselInMPA, etc.)
    /// </summary>
    public required AlertType Type { get; set; }

    /// <summary>
    /// Severity level of alerts generated by this rule
    /// </summary>
    public AlertSeverity Severity { get; set; } = AlertSeverity.Medium;

    /// <summary>
    /// Whether this rule is currently active
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// JSON-serialized conditions for the rule
    /// </summary>
    public required string Conditions { get; set; }

    /// <summary>
    /// Optional: specific MPA to monitor (null = all MPAs)
    /// </summary>
    public Guid? MarineProtectedAreaId { get; set; }
    public MarineProtectedArea? MarineProtectedArea { get; set; }

    /// <summary>
    /// Notification channels (Email, Push, Dashboard)
    /// </summary>
    public NotificationChannel NotificationChannels { get; set; } = NotificationChannel.Dashboard;

    /// <summary>
    /// Email addresses for notifications (comma-separated)
    /// </summary>
    public string? NotificationEmails { get; set; }

    /// <summary>
    /// Cooldown period between alerts (prevents spam)
    /// </summary>
    public TimeSpan CooldownPeriod { get; set; } = TimeSpan.FromHours(1);

    /// <summary>
    /// Last time this rule triggered an alert
    /// </summary>
    public DateTime? LastTriggeredAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Alerts generated by this rule
    /// </summary>
    public ICollection<Alert> Alerts { get; set; } = new List<Alert>();
}
